// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1FtHk01eTg2kBjM9xCv6pWzhvfr8saig',
    appId: '1:156526871941:android:ca35dacf838729bdb530ec',
    messagingSenderId: '156526871941',
    projectId: 'fir-lab-45f80',
    storageBucket: 'fir-lab-45f80.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2K2ur5AAgpLBu2qANcIUexDXhss1Qcqw',
    appId: '1:156526871941:ios:8233d7448f4287b4b530ec',
    messagingSenderId: '156526871941',
    projectId: 'fir-lab-45f80',
    storageBucket: 'fir-lab-45f80.appspot.com',
    iosClientId: '156526871941-vhdc360m2mu2q84e2bbbsllhm2ib9dh4.apps.googleusercontent.com',
    iosBundleId: 'com.example.demoFirebaseSearch',
  );
}
